LangString LauncherFileNotFound ${LANG_THAI} "${PORTABLEAPPNAME} ไม่สามารถเริ่มได้ คุณอาจต้องการติดตั้งใหม่เพื่อแก้ไขปัญหานี้ (ข้อผิดพลาด: ไม่พบ $MISSINGFILEORPATH)"
LangString LauncherAlreadyRunning ${LANG_THAI} "อินสแตนซ์อื่นของ ${APPNAME} กำลังทำงานอยู่แล้ว โปรดปิดอินสแตนซ์อื่นๆ ของ ${APPNAME} ก่อนเปิดตัว ${PORTABLEAPPNAME}"
LangString LauncherAskCopyLocal ${LANG_THAI} "ดูเหมือนว่า ${PORTABLEAPPNAME} จะทำงานจากตำแหน่งที่อ่านอย่างเดียว คุณต้องการคัดลอกไปยังฮาร์ดไดรฟ์ในเครื่องชั่วคราวและเรียกใช้จากที่นั่นหรือไม่$\n$\nหมายเหตุเกี่ยวกับความเป็นส่วนตัว: หากคุณตอบว่าใช่ ข้อมูลส่วนบุคคลของคุณภายใน ${PORTABLEAPPNAME} จะถูกคัดลอกไปยังไดรฟ์ในเครื่องชั่วคราว แม้ว่าสำเนาข้อมูลของคุณนี้จะถูกลบออกเมื่อคุณปิด ${PORTABLEAPPNAME} แต่บุคคลอื่นอาจเข้าถึงข้อมูลของคุณได้ในภายหลัง"
LangString LauncherNoReadOnly ${LANG_THAI} "${PORTABLEAPPNAME} ไม่สามารถเรียกใช้ได้โดยตรงจากตำแหน่งแบบอ่านอย่างเดียว และตอนนี้จะปิดลง"
LangString LauncherPathTooLong ${LANG_THAI} "เส้นทางไปยัง ${PORTABLEAPPNAME} ยาวเกินไป โปรดย่อพาธโดยกำจัดไดเร็กทอรีหลักหรือย่อชื่อไดเร็กทอรี"
LangString LauncherNextButton ${LANG_THAI} "ถัดไป >"
